name: citysewa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.2.1
  carousel_slider: ^5.1.1
  flutter_html: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_icons:
  android: true
  image_path: "lib/assets/app_icon.png"
  adaptive_icon_background: "#ff0000"
  adaptive_icon_foreground: "lib/assets/app_icon.png"
